config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :resources  do
    member do
      get :mark_complete
      get :mark_incomplete
    end
  end
  resources :notes, only: [:create]
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :resource, counter_cache: :notes_count
  validates :text, presence: true
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :user
  has_many :notes
  validates :title, presence: true

  self.per_page = 10

  scope :completed,   -> { where.not(completed_at: nil) }
  scope :incompleted, -> { where(completed_at: nil) }

  def mark_complete
    touch :completed_at
  end

  def completed?
    completed_at
  end

  def mark_incomplete
    update(completed_at: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :resources, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    resources_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @resource = current_user.resources.find(params[:note][:resource_id])
    @note = @resource.notes.build(note_params)
    if @note.save
      flash[:success] = 'Note added'
      redirect_to @resource
    else
      render 'resources/show'
    end
  end

  private

  def note_params
    params.require(:note).permit(:text)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :redirect_logged_in_user, only: :index

  def index
  end

  private

  def redirect_logged_in_user
    redirect_to resources_path if user_signed_in?
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_user!

  def index
    @resources = apply_filter(params).paginate(page: params[:page])
  end

  def show
    @resource = Resource.find(params[:id])
    @note = Note.new
  end

  def new
    @resource = Resource.new
  end

  def create
    @resource = current_user.resources.build(resource_params)
    if @resource.save
      flash[:success] = 'Resource added.'
      redirect_to @resource
    else
      render :new
    end
  end

  def edit
    @resource = resource
  end

  def update
    @resource = resource
    if @resource.update_attributes(resource_params)
      flash[:success] = 'Resource updated.'
      redirect_to @resource
    else
      render :edit
    end
  end

  def destroy
    resource.destroy
    redirect_to params[:no_way_back].present? ? resources_url : :back
  end

  def mark_complete
    resource.mark_complete
    redirect_to :back
  end

  def mark_incomplete
    resource.mark_incomplete
    redirect_to :back
  end

  private

  def resource_params
    params.require(:resource).permit(:title, :description)
  end

  def resource
    current_user.resources.find(params[:id])
  end

  def apply_filter(params)
    if params[:status] == 'completed'
      current_user.resources.completed
    elsif params[:status] == 'incompleted'
      current_user.resources.incompleted
    else
      current_user.resources
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_errors_for(resource)
    if resource.errors.any?
      content_tag :ul do
        resource.errors.full_messages.each do |msg|
          concat(content_tag(:li, msg))
        end
      end
    end
  end
end

app/helpers/resources_helper.rb
module ResourcesHelper

  def added_on(time)
    time.strftime('%b %d')
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{yield(:title)} | Pump
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render 'shared/header' if user_signed_in?
    .container
      .page-header
        h1 = yield(:title)
      = yield

app/views/notes/_note.html.slim
= note.text

app/views/pages/index.html.slim
- provide(:title, 'Welcome')

= link_to 'Sign in', new_user_session_path

app/views/resources/_resource.html.slim
.row
  .col-md-12
    .bs-callout class=(resource.completed? ? 'bs-callout-complete' : 'bs-callout-incomplete')
      h4
        = link_to resource.title, resource_path(resource)
        small.pull-right added on #{added_on(resource.created_at)}
      p = resource.description
      = render partial: 'shared/resource_completion_link', locals: { resource: resource }
      = link_to 'Delete', resource_path(resource), method: :delete
      | Notes(#{resource.notes.size})

app/views/resources/edit.html.slim
- provide(:title, 'Edit resource')

= render partial: 'shared/resource_form', locals: { resource: @resource }

app/views/resources/index.html.slim
- provide(:title, 'Resources')

.row
  .col-md-12.controls
    = link_to 'Add resource', new_resource_path, class: 'btn btn-default'
    | Filter by: 
    = link_to 'Completed', resources_path(status: 'completed')
    = link_to 'Not completed', resources_path(status: 'incompleted')
    
= render @resources
.row
  .col-md-12.text-center
    = will_paginate @resources, renderer: BootstrapPagination::Rails

app/views/resources/new.html.slim
- provide(:title, 'Add a new resource')

= form_errors_for(@resource)
= form_for @resource do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  = f.submit 'Add'

app/views/resources/show.html.slim
- provide(:title, @resource.title)

= @resource.title
= @resource.description

= render partial: 'shared/resource_completion_link', locals: { resource: @resource }
= link_to 'Delete', resource_path(@resource, no_way_back: '1'), method: :delete
= link_to 'Edit', edit_resource_path(@resource)

= form_errors_for @note
= form_for @note do |f|
  = f.hidden_field :resource_id, value: @resource.id
  = f.label :text, 'Add note'
  = f.text_area :text
  = f.submit 'Add'

= render @resource.notes

app/views/shared/_header.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      = link_to 'PUMP', root_path, class: 'navbar-brand'
    ul.nav.navbar-nav
      li = link_to 'Resources', resources_path
      li = link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/shared/_resource_completion_link.html.slim
- if resource.completed?
  = link_to 'Mark incomplete', mark_incomplete_resource_path(resource)
- else
  = link_to 'Mark complete', mark_complete_resource_path(resource)

app/views/shared/_resource_form.html.slim
= form_errors_for(resource)
= form_for resource do |f|
  = f.label :title
  = f.text_field :title
  = f.label :description
  = f.text_area :description
  = f.submit 'Submit'